name: Merges pull requests
on:
  schedule:
    - cron: '* * * * *'

jobs:
  pull-request-reviewer-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install & run
        run: |
          npm install --production
          ./node_modules/.bin/ts-node src/main.ts
        env:
          TOKEN: ${{ secrets.TOKEN }}