name: 'Pull request reviewer reminder'
on:
  schedule:
    - cron: '* * * * *'

jobs:
  pull-request-reviewer-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Build & run
        run: |
          npm install --production
          ./node_modules/.bin/ts-node src/main-pr-review-reminders.ts
