name: 'Pull request reviewer reminder'
on:
  schedule:
    - cron: '* * * * *'

jobs:
  pull-request-reviewer-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: npm i

      - name: notify
        run: ./node_modules/.bin/ts-node src/main-pr-review-reminders.ts

